packages:
  - 'apps/*'
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': set this to true or false
  bcrypt: true
  better-sqlite3: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react@1.29.0 || 1.30.0
